//
// Generated file, do not edit! Created by opp_msgtool 6.3 from simu5g/stack/compManager/X2CompReplyIE.msg.
//

#ifndef __SIMU5G_X2COMPREPLYIE_M_H
#define __SIMU5G_X2COMPREPLYIE_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0603
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif


namespace simu5g {

class X2CompReplyIE;

}  // namespace simu5g

#include "simu5g/x2/packet/X2InformationElement_m.h" // import simu5g.x2.packet.X2InformationElement


namespace simu5g {

/**
 * Class generated from <tt>simu5g/stack/compManager/X2CompReplyIE.msg:17</tt> by opp_msgtool.
 * <pre>
 * class X2CompReplyIE extends X2InformationElement
 * {
 *     type = COMP_REPLY_IE;
 *     length = 0;
 * }
 * </pre>
 */
class X2CompReplyIE : public ::simu5g::X2InformationElement
{
  protected:

  private:
    void copy(const X2CompReplyIE& other);

  protected:
    bool operator==(const X2CompReplyIE&) = delete;

  public:
    X2CompReplyIE();
    X2CompReplyIE(const X2CompReplyIE& other);
    virtual ~X2CompReplyIE();
    X2CompReplyIE& operator=(const X2CompReplyIE& other);
    virtual X2CompReplyIE *dup() const override {return new X2CompReplyIE(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const X2CompReplyIE& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, X2CompReplyIE& obj) {obj.parsimUnpack(b);}


}  // namespace simu5g


namespace omnetpp {

template<> inline simu5g::X2CompReplyIE *fromAnyPtr(any_ptr ptr) { return check_and_cast<simu5g::X2CompReplyIE*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __SIMU5G_X2COMPREPLYIE_M_H

