//
// Generated file, do not edit! Created by opp_msgtool 6.3 from simu5g/stack/rlc/am/packet/LteRlcAmPdu.msg.
//

#ifndef __SIMU5G_LTERLCAMPDU_M_H
#define __SIMU5G_LTERLCAMPDU_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0603
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif


namespace simu5g {

class LteRlcAmPdu;

}  // namespace simu5g

#include "simu5g/stack/rlc/LteRlcDefs_m.h" // import simu5g.stack.rlc.LteRlcDefs

#include "simu5g/stack/rlc/packet/LteRlcPdu_m.h" // import simu5g.stack.rlc.packet.LteRlcPdu


namespace simu5g {

/**
 * Class generated from <tt>simu5g/stack/rlc/am/packet/LteRlcAmPdu.msg:18</tt> by opp_msgtool.
 * <pre>
 * class LteRlcAmPdu extends LteRlcPdu
 * {
 *     unsigned short amType \@enum(LteAmType);
 *     unsigned short txNumber;
 *     int firstSn;
 *     int lastSn;
 *     bool bitmap[] \@custom;
 * }
 * </pre>
 */
class LteRlcAmPdu : public ::LteRlcPdu
{
  protected:
    unsigned short amType = 0;
    unsigned short txNumber = 0;
    int firstSn = 0;
    int lastSn = 0;

  private:
    void copy(const LteRlcAmPdu& other);

  protected:
    bool operator==(const LteRlcAmPdu&) = delete;

  public:
    LteRlcAmPdu();
    LteRlcAmPdu(const LteRlcAmPdu& other);
    virtual ~LteRlcAmPdu();
    LteRlcAmPdu& operator=(const LteRlcAmPdu& other);
    virtual LteRlcAmPdu *dup() const override {return new LteRlcAmPdu(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual unsigned short getAmType() const;
    virtual void setAmType(unsigned short amType);

    virtual unsigned short getTxNumber() const;
    virtual void setTxNumber(unsigned short txNumber);

    virtual int getFirstSn() const;
    virtual void setFirstSn(int firstSn);

    virtual int getLastSn() const;
    virtual void setLastSn(int lastSn);


  protected:
    // bitmap[] custom data
    std::vector<bool> bitmap_;

  public:
    // bitmap[] custom functions
    virtual size_t getBitmapArraySize() const { return bitmap_.size(); }
    virtual void setBitmapArraySize(size_t size) { bitmap_.resize(size); }
    virtual bool getBitmap(size_t k) const { return bitmap_.at(k); }
    virtual void setBitmap(size_t k, bool bitmap_var) { bitmap_[k] = bitmap_var; }
    virtual void appendBitmap(bool bitmap) { throw cRuntimeError("Method not implemented"); }
    virtual void insertBitmap(size_t k, bool bitmap) { throw cRuntimeError("Method not implemented"); }
    virtual void eraseBitmap(size_t k) { throw cRuntimeError("Method not implemented"); }

    // bitmap[] direct access functions
    virtual const std::vector<bool>& getBitmapVec() const { return bitmap_; }
    void setBitmapVec(const std::vector<bool>& bitmap_vec) { handleChange(); bitmap_ = bitmap_vec; }

    // sequence check functions
    virtual bool isWhole() const { return firstSn == lastSn; }
    virtual bool isFirst() const { return firstSn == snoFragment; }
    virtual bool isMiddle() const { return !isFirst() && !isLast(); }
    virtual bool isLast() const { return lastSn == snoFragment; }
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const LteRlcAmPdu& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, LteRlcAmPdu& obj) {obj.parsimUnpack(b);}


}  // namespace simu5g


namespace omnetpp {

template<> inline simu5g::LteRlcAmPdu *fromAnyPtr(any_ptr ptr) { return check_and_cast<simu5g::LteRlcAmPdu*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __SIMU5G_LTERLCAMPDU_M_H

