//
// Generated file, do not edit! Created by opp_msgtool 6.3 from simu5g/x2/packet/LteX2Message.msg.
//

#ifndef __SIMU5G_LTEX2MESSAGE_M_H
#define __SIMU5G_LTEX2MESSAGE_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0603
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif


namespace simu5g {

class LteX2Message;

}  // namespace simu5g

#include "inet/common/INETDefs_m.h" // import inet.common.INETDefs

#include "inet/common/packet/chunk/Chunk_m.h" // import inet.common.packet.chunk.Chunk

#include "simu5g/common/LteCommon_m.h" // import simu5g.common.LteCommon

#include "simu5g/x2/packet/X2InformationElement_m.h" // import simu5g.x2.packet.X2InformationElement


namespace simu5g {

/**
 * Enum generated from <tt>simu5g/x2/packet/LteX2Message.msg:21</tt> by opp_msgtool.
 * <pre>
 * // add here new X2 message types
 * enum LteX2MessageType
 * {
 *     X2_COMP_MSG = 0;
 *     X2_HANDOVER_CONTROL_MSG = 1;
 *     X2_HANDOVER_DATA_MSG = 2;
 *     X2_DUALCONNECTIVITY_CONTROL_MSG = 3;
 *     X2_DUALCONNECTIVITY_DATA_MSG = 4;
 *     X2_UNKNOWN_MSG = 5;
 * }
 * </pre>
 */
enum LteX2MessageType {
    X2_COMP_MSG = 0,
    X2_HANDOVER_CONTROL_MSG = 1,
    X2_HANDOVER_DATA_MSG = 2,
    X2_DUALCONNECTIVITY_CONTROL_MSG = 3,
    X2_DUALCONNECTIVITY_DATA_MSG = 4,
    X2_UNKNOWN_MSG = 5
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const LteX2MessageType& e) { b->pack(static_cast<int>(e)); }
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, LteX2MessageType& e) { int n; b->unpack(n); e = static_cast<LteX2MessageType>(n); }

/**
 * Class generated from <tt>simu5g/x2/packet/LteX2Message.msg:36</tt> by opp_msgtool.
 * <pre>
 * //
 * // This is the X2 message flowing through X2 interface.
 * // It contains a vector of Information Elements (see LteX2Message.h),
 * // the total length of the message and the type of the message
 * //
 * class LteX2Message extends inet::FieldsChunk
 * {
 *     chunkLength = inet::B(11); // FIXME needs to be checked:
 *                                // realistic chunk length without X2 information elements?
 *                                // Must at least be 11 Bytes for serialization:
 *                                // Type (1 B), sourceId (4 B), destinationId (4 B), IE list size (2 B))
 *     MacNodeId sourceId;
 *     MacNodeId destinationId;
 * 
 *     /// type of the X2 message
 *     LteX2MessageType type = X2_UNKNOWN_MSG;
 * 
 *     /// Size of the X2 message
 *     int64_t msgLength = 0;
 * 
 *     /// List of X2 IEs
 *     X2InformationElement *ie[] \@owned;
 * }
 * </pre>
 */
class LteX2Message : public ::inet::FieldsChunk
{
  protected:
    MacNodeId sourceId;
    MacNodeId destinationId;
    LteX2MessageType type = X2_UNKNOWN_MSG;
    int64_t msgLength = 0;
    X2InformationElement * *ie = nullptr;
    size_t ie_arraysize = 0;

  private:
    void copy(const LteX2Message& other);

  protected:
    bool operator==(const LteX2Message&) = delete;

  public:
    LteX2Message();
    LteX2Message(const LteX2Message& other);
    virtual ~LteX2Message();
    LteX2Message& operator=(const LteX2Message& other);
    virtual LteX2Message *dup() const override {return new LteX2Message(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual MacNodeId getSourceId() const;
    virtual void setSourceId(MacNodeId sourceId);

    virtual MacNodeId getDestinationId() const;
    virtual void setDestinationId(MacNodeId destinationId);

    virtual LteX2MessageType getType() const;
    virtual void setType(LteX2MessageType type);

    virtual int64_t getMsgLength() const;
    virtual void setMsgLength(int64_t msgLength);

    virtual void setIeArraySize(size_t size);
    virtual size_t getIeArraySize() const;
    virtual const X2InformationElement * getIe(size_t k) const;
    virtual X2InformationElement * getIeForUpdate(size_t k) { handleChange();return const_cast<X2InformationElement *>(const_cast<LteX2Message*>(this)->getIe(k));}
    virtual void setIe(size_t k, X2InformationElement * ie);
    virtual X2InformationElement * removeIe(size_t k);
    [[deprecated]] X2InformationElement * dropIe(size_t k) {return removeIe(k);}
    virtual void insertIe(size_t k, X2InformationElement * ie);
    [[deprecated]] void insertIe(X2InformationElement * ie) {appendIe(ie);}
    virtual void appendIe(X2InformationElement * ie);
    virtual void eraseIe(size_t k);


  public:
    /**
     * pushIe() stores an IE inside the
     * X2 IE list in back position and updates msg length
     *
     * @param ie IE to store
     */
    virtual void pushIe(X2InformationElement *ie) {
        appendIe(ie);
        msgLength += ie->getLength();
        // increase the chunk length by length of IE + 1 Byte (required to store the IE type)
        setChunkLength(getChunkLength() + inet::b(8 * (ie->getLength() + sizeof(uint8_t))));
        // EV << "pushIe: pushed an element of length: " << ie->getLength() << " new chunk length: " << getChunkLength() << std::endl;
    }

    /**
     * popIe() pops an IE from the front of
     * the IE list and returns it
     *
     * @return popped IE
     */
    virtual X2InformationElement *popIe() {
        X2InformationElement *ie = removeIe(0);
        eraseIe(0);

        msgLength -= ie->getLength();
        // chunk is immutable during serialization!
        // (chunk length can therefore not be adapted - we only adapt the separate msg_Length_)

        return ie;
    }

    /**
     * hasIe() verifies if there are other
     * IEs inside the IE list
     *
     * @return true if list is not empty, false otherwise
     */
    virtual bool hasIe() const { return ie_arraysize != 0; }

    int64_t getByteLength() const { return msgLength; }

    int64_t getBitLength() const { return getByteLength() * 8; }
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const LteX2Message& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, LteX2Message& obj) {obj.parsimUnpack(b);}


}  // namespace simu5g


namespace omnetpp {

template<> inline simu5g::LteX2Message *fromAnyPtr(any_ptr ptr) { return check_and_cast<simu5g::LteX2Message*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __SIMU5G_LTEX2MESSAGE_M_H

