//
// Generated file, do not edit! Created by opp_msgtool 6.3 from simu5g/x2/packet/X2InformationElement.msg.
//

#ifndef __SIMU5G_X2INFORMATIONELEMENT_M_H
#define __SIMU5G_X2INFORMATIONELEMENT_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0603
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif


namespace simu5g {

class X2InformationElement;

}  // namespace simu5g


namespace simu5g {

/**
 * Enum generated from <tt>simu5g/x2/packet/X2InformationElement.msg:16</tt> by opp_msgtool.
 * <pre>
 * // add here new IE types
 * enum X2InformationElementType
 * {
 *     COMP_REQUEST_IE = 0;         // CoMP slave -> master
 *     COMP_REPLY_IE = 1;           // CoMP master -> slave
 *     COMP_PROP_REQUEST_IE = 2;    // CoMP slave -> master (for compManagerProportional, with RB value)
 *     COMP_PROP_REPLY_IE = 3;      // CoMP master -> slave (for compManagerProportional, with map)
 *     X2_HANDOVER_CMD_IE = 4;      // HO command source eNB -> target eNB
 * }
 * </pre>
 */
enum X2InformationElementType {
    COMP_REQUEST_IE = 0,
    COMP_REPLY_IE = 1,
    COMP_PROP_REQUEST_IE = 2,
    COMP_PROP_REPLY_IE = 3,
    X2_HANDOVER_CMD_IE = 4
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const X2InformationElementType& e) { b->pack(static_cast<int>(e)); }
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, X2InformationElementType& e) { int n; b->unpack(n); e = static_cast<X2InformationElementType>(n); }

/**
 * Class generated from <tt>simu5g/x2/packet/X2InformationElement.msg:30</tt> by opp_msgtool.
 * <pre>
 * //
 * // X2 Information Element
 * //
 * // Extend this class to define new Information Elements
 * //
 * class X2InformationElement extends cObject
 * {
 *     X2InformationElementType type;
 *     int64_t length;  // Length in bytes
 * }
 * </pre>
 */
class X2InformationElement : public ::omnetpp::cObject
{
  protected:
    X2InformationElementType type = static_cast<simu5g::X2InformationElementType>(-1);
    int64_t length = 0;

  private:
    void copy(const X2InformationElement& other);

  protected:
    bool operator==(const X2InformationElement&) = delete;

  public:
    X2InformationElement();
    X2InformationElement(const X2InformationElement& other);
    virtual ~X2InformationElement();
    X2InformationElement& operator=(const X2InformationElement& other);
    virtual X2InformationElement *dup() const override {return new X2InformationElement(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual X2InformationElementType getType() const;
    virtual void setType(X2InformationElementType type);

    virtual int64_t getLength() const;
    virtual void setLength(int64_t length);


  public:
    X2InformationElement(X2InformationElementType type) : type(type) {}
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const X2InformationElement& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, X2InformationElement& obj) {obj.parsimUnpack(b);}


}  // namespace simu5g


namespace omnetpp {

template<> inline simu5g::X2InformationElement *fromAnyPtr(any_ptr ptr) { return check_and_cast<simu5g::X2InformationElement*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __SIMU5G_X2INFORMATIONELEMENT_M_H

