//
// Generated file, do not edit! Created by opp_msgtool 6.3 from simu5g/stack/phy/packet/LteAirFrame.msg.
//

#ifndef __SIMU5G_LTEAIRFRAME_M_H
#define __SIMU5G_LTEAIRFRAME_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0603
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif


namespace simu5g {

class LteAirFrame;

}  // namespace simu5g

#include "simu5g/stack/phy/packet/AirFrame_m.h" // import simu5g.stack.phy.packet.AirFrame

// cplusplus {{
#include "simu5g/common/LteCommon.h"  // for RemoteUnitPhyDataVector
// }}


namespace simu5g {

/**
 * Class generated from <tt>simu5g/stack/phy/packet/LteAirFrame.msg:29</tt> by opp_msgtool.
 * <pre>
 * //
 * // Represents a physical layer transmission frame that encapsulates various types of
 * // messages/packets for transmission over the air interface, such as:
 * // - MAC PDUs (user data): transmitted as Transport Blocks (TB) on PDSCH/PUSCH
 * // - HARQ feedback: transmitted on PUCCH (uplink control channel)
 * // - Scheduling grants (DCI): transmitted on PDCCH (downlink control channel)
 * // - Random access and D2D packets: transmitted on respective control/data channels
 * // In the simulation, all these messages types are abstracted as LteAirFrame transmissions.
 * //
 * packet LteAirFrame extends AirFrame
 * {
 *     \@customize(true);
 *     RemoteUnitPhyData remoteUnitPhyDataVector[] \@nopack;
 * }
 * </pre>
 *
 * LteAirFrame_Base is only useful if it gets subclassed, and LteAirFrame is derived from it.
 * The minimum code to be written for LteAirFrame is the following:
 *
 * <pre>
 * class LteAirFrame : public LteAirFrame_Base
 * {
 *   private:
 *     void copy(const LteAirFrame& other) { ... }

 *   public:
 *     LteAirFrame(const char *name=nullptr, short kind=0) : LteAirFrame_Base(name,kind) {}
 *     LteAirFrame(const LteAirFrame& other) : LteAirFrame_Base(other) {copy(other);}
 *     LteAirFrame& operator=(const LteAirFrame& other) {if (this==&other) return *this; LteAirFrame_Base::operator=(other); copy(other); return *this;}
 *     virtual LteAirFrame *dup() const override {return new LteAirFrame(*this);}
 *     // ADD CODE HERE to redefine and implement pure virtual functions from LteAirFrame_Base
 * };
 * </pre>
 *
 * The following should go into a .cc (.cpp) file:
 *
 * <pre>
 * Register_Class(LteAirFrame)
 * </pre>
 */
class LteAirFrame_Base : public ::simu5g::AirFrame
{
  protected:
    RemoteUnitPhyData *remoteUnitPhyDataVector = nullptr;
    size_t remoteUnitPhyDataVector_arraysize = 0;

  private:
    void copy(const LteAirFrame_Base& other);

  protected:
    bool operator==(const LteAirFrame_Base&) = delete;
    // make constructors protected to avoid instantiation
    LteAirFrame_Base(const char *name=nullptr, short kind=0);
    LteAirFrame_Base(const LteAirFrame_Base& other);
    // make assignment operator protected to force the user override it
    LteAirFrame_Base& operator=(const LteAirFrame_Base& other);

  public:
    virtual ~LteAirFrame_Base();
    virtual LteAirFrame_Base *dup() const override {throw omnetpp::cRuntimeError("You forgot to manually add a dup() function to class LteAirFrame");}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual void setRemoteUnitPhyDataVectorArraySize(size_t size);
    virtual size_t getRemoteUnitPhyDataVectorArraySize() const;
    virtual const RemoteUnitPhyData& getRemoteUnitPhyDataVector(size_t k) const;
    virtual RemoteUnitPhyData& getRemoteUnitPhyDataVectorForUpdate(size_t k) { return const_cast<RemoteUnitPhyData&>(const_cast<LteAirFrame_Base*>(this)->getRemoteUnitPhyDataVector(k));}
    virtual void setRemoteUnitPhyDataVector(size_t k, const RemoteUnitPhyData& remoteUnitPhyDataVector);
    virtual void insertRemoteUnitPhyDataVector(size_t k, const RemoteUnitPhyData& remoteUnitPhyDataVector);
    [[deprecated]] void insertRemoteUnitPhyDataVector(const RemoteUnitPhyData& remoteUnitPhyDataVector) {appendRemoteUnitPhyDataVector(remoteUnitPhyDataVector);}
    virtual void appendRemoteUnitPhyDataVector(const RemoteUnitPhyData& remoteUnitPhyDataVector);
    virtual void eraseRemoteUnitPhyDataVector(size_t k);


  public:
    void addRemoteUnitPhyDataVector(const RemoteUnitPhyData& data) { appendRemoteUnitPhyDataVector(data); }
};


}  // namespace simu5g


namespace omnetpp {

template<> inline simu5g::LteAirFrame_Base *fromAnyPtr(any_ptr ptr) { return check_and_cast<simu5g::LteAirFrame_Base*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __SIMU5G_LTEAIRFRAME_M_H

