//
// Generated file, do not edit! Created by opp_msgtool 6.3 from simu5g/stack/phy/packet/LteFeedbackPkt.msg.
//

#ifndef __SIMU5G_LTEFEEDBACKPKT_M_H
#define __SIMU5G_LTEFEEDBACKPKT_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0603
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif


namespace simu5g {

class LteFeedbackPkt;

}  // namespace simu5g

#include "inet/common/INETDefs_m.h" // import inet.common.INETDefs

#include "inet/common/packet/chunk/Chunk_m.h" // import inet.common.packet.chunk.Chunk

#include "simu5g/common/LteCommon_m.h" // import simu5g.common.LteCommon

// cplusplus {{
#include "simu5g/stack/phy/feedback/LteFeedback.h"
// }}


namespace simu5g {

/**
 * Class generated from <tt>simu5g/stack/phy/packet/LteFeedbackPkt.msg:22</tt> by opp_msgtool.
 * <pre>
 * class LteFeedbackPkt extends inet::FieldsChunk
 * {
 *     chunkLength = inet::B(1); // TODO: size 0
 * 
 *     // MacNodeId of the source
 *     MacNodeId sourceNodeId;
 * }
 * </pre>
 */
class LteFeedbackPkt : public ::inet::FieldsChunk
{
  protected:
    MacNodeId sourceNodeId;

  private:
    void copy(const LteFeedbackPkt& other);

  protected:
    bool operator==(const LteFeedbackPkt&) = delete;

  public:
    LteFeedbackPkt();
    LteFeedbackPkt(const LteFeedbackPkt& other);
    virtual ~LteFeedbackPkt();
    LteFeedbackPkt& operator=(const LteFeedbackPkt& other);
    virtual LteFeedbackPkt *dup() const override {return new LteFeedbackPkt(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual MacNodeId getSourceNodeId() const;
    virtual void setSourceNodeId(MacNodeId sourceNodeId);


  protected:
    // vector of vectors with RU and TxMode as indexes
    LteFeedbackDoubleVector lteFeedbackDoubleVectorDl_;
    // vector of vectors with RU and TxMode as indexes
    LteFeedbackDoubleVector lteFeedbackDoubleVectorUl_;
    // map of vectors of vectors with peering UEs, RUs, and TxModes as indexes
    std::map<MacNodeId, LteFeedbackDoubleVector> lteFeedbackMapDoubleVectorD2D_;

  public:
    LteFeedbackDoubleVector getLteFeedbackDoubleVectorDl() const;
    void setLteFeedbackDoubleVectorDl(LteFeedbackDoubleVector lteFeedbackDoubleVector_);
    LteFeedbackDoubleVector getLteFeedbackDoubleVectorUl() const;
    void setLteFeedbackDoubleVectorUl(LteFeedbackDoubleVector lteFeedbackDoubleVector_);
    std::map<MacNodeId, LteFeedbackDoubleVector> getLteFeedbackDoubleVectorD2D() const;
    void setLteFeedbackDoubleVectorD2D(MacNodeId peerId, LteFeedbackDoubleVector lteFeedbackDoubleVector_);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const LteFeedbackPkt& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, LteFeedbackPkt& obj) {obj.parsimUnpack(b);}


}  // namespace simu5g


namespace omnetpp {

template<> inline simu5g::LteFeedbackPkt *fromAnyPtr(any_ptr ptr) { return check_and_cast<simu5g::LteFeedbackPkt*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __SIMU5G_LTEFEEDBACKPKT_M_H

