//
// Generated file, do not edit! Created by opp_msgtool 6.3 from simu5g/stack/phy/packet/ModulationType.msg.
//

#ifndef __SIMU5G_MODULATIONTYPE_M_H
#define __SIMU5G_MODULATIONTYPE_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0603
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif


namespace simu5g {

class ModulationType;

}  // namespace simu5g


namespace simu5g {

/**
 * Enum generated from <tt>simu5g/stack/phy/packet/ModulationType.msg:23</tt> by opp_msgtool.
 * <pre>
 * enum ModulationClass
 * {
 *     // Modulation class unknown or unspecified. A WifiMode with this WifiModulationClass has not been properly initialized.
 *     MOD_CLASS_UNKNOWN = 0;
 *     // Infrared (IR) (Clause 16)
 *     MOD_CLASS_IR = 1;
 *     // Frequency-hopping spread spectrum (FHSS) PHY (Clause 14)
 *     MOD_CLASS_FHSS = 2;
 *     // DSSS PHY (Clause 15) and HR/DSSS PHY (Clause 18)
 *     MOD_CLASS_DSSS = 3;
 *     // ERP-PBCC PHY (19.6)
 *     MOD_CLASS_ERP_PBCC = 4;
 *     // DSSS-OFDM PHY (19.7)
 *     MOD_CLASS_DSSS_OFDM = 5;
 *     // ERP-OFDM PHY (19.5)
 *     MOD_CLASS_ERP_OFDM = 6;
 *     // OFDM PHY (Clause 17)
 *     MOD_CLASS_OFDM = 7;
 *     // HT PHY (Clause 20)
 *     MOD_CLASS_HT = 8;
 * }
 * </pre>
 */
enum ModulationClass {
    MOD_CLASS_UNKNOWN = 0,
    MOD_CLASS_IR = 1,
    MOD_CLASS_FHSS = 2,
    MOD_CLASS_DSSS = 3,
    MOD_CLASS_ERP_PBCC = 4,
    MOD_CLASS_DSSS_OFDM = 5,
    MOD_CLASS_ERP_OFDM = 6,
    MOD_CLASS_OFDM = 7,
    MOD_CLASS_HT = 8
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const ModulationClass& e) { b->pack(static_cast<int>(e)); }
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, ModulationClass& e) { int n; b->unpack(n); e = static_cast<ModulationClass>(n); }

/**
 * Enum generated from <tt>simu5g/stack/phy/packet/ModulationType.msg:51</tt> by opp_msgtool.
 * <pre>
 * //
 * // This enumeration defines the various convolutional coding rates
 * // used for the OFDM transmission modes in the IEEE 802.11
 * // standard. DSSS (for example) rates which do not have an explicit
 * // coding stage in their generation should have this parameter set to
 * // WIFI_CODE_RATE_UNDEFINED.
 * //
 * enum CodeRate
 * {
 *     // No explicit coding (e.g., DSSS rates)
 *     CODE_RATE_UNDEFINED = 0;
 *     // Rate 3/4
 *     CODE_RATE_3_4 = 1;
 *     // Rate 2/3
 *     CODE_RATE_2_3 = 2;
 *     // Rate 1/2
 *     CODE_RATE_1_2 = 3;
 *     // Rate 5/6
 *     CODE_RATE_5_6 = 4;
 * }
 * </pre>
 */
enum CodeRate {
    CODE_RATE_UNDEFINED = 0,
    CODE_RATE_3_4 = 1,
    CODE_RATE_2_3 = 2,
    CODE_RATE_1_2 = 3,
    CODE_RATE_5_6 = 4
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const CodeRate& e) { b->pack(static_cast<int>(e)); }
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, CodeRate& e) { int n; b->unpack(n); e = static_cast<CodeRate>(n); }

/**
 * Class generated from <tt>simu5g/stack/phy/packet/ModulationType.msg:73</tt> by opp_msgtool.
 * <pre>
 * //
 * // \brief Represents a single transmission mode
 * //
 * // A WifiMode is implemented by a single integer which is used
 * // to lookup in a global array the characteristics of the
 * // associated transmission mode. It is thus extremely cheap to
 * // keep a WifiMode variable around.
 * //
 * class ModulationType
 * {
 *     bool isMandatory \@getter(getIsMandatory) = false;
 *     uint32_t bandwidth = 0;
 *     uint32_t dataRate = 0;
 *     /// MANDATORY it is necessary to set the dataRate before the codeRate
 *     CodeRate codeRate = CODE_RATE_UNDEFINED;
 *     uint32_t phyRate = 0;
 *     uint8_t constellationSize = 0;
 *     ModulationClass modulationClass = MOD_CLASS_UNKNOWN;
 *     uint32_t frequency = 2400;
 * }
 * </pre>
 */
class ModulationType
{
  protected:
    bool isMandatory = false;
    uint32_t bandwidth = 0;
    uint32_t dataRate = 0;
    CodeRate codeRate = CODE_RATE_UNDEFINED;
    uint32_t phyRate = 0;
    uint8_t constellationSize = 0;
    ModulationClass modulationClass = MOD_CLASS_UNKNOWN;
    uint32_t frequency = 2400;

  private:
    void copy(const ModulationType& other);

  protected:
    bool operator==(const ModulationType&) = delete;

  public:
    ModulationType();
    ModulationType(const ModulationType& other);
    virtual ~ModulationType();
    ModulationType& operator=(const ModulationType& other);
    virtual void parsimPack(omnetpp::cCommBuffer *b) const;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b);

    virtual bool getIsMandatory() const;
    virtual void setIsMandatory(bool isMandatory);

    virtual uint32_t getBandwidth() const;
    virtual void setBandwidth(uint32_t bandwidth);

    virtual uint32_t getDataRate() const;
    virtual void setDataRate(uint32_t dataRate);

    virtual CodeRate getCodeRate() const;
    virtual void setCodeRate(CodeRate codeRate);

    virtual uint32_t getPhyRate() const;
    virtual void setPhyRate(uint32_t phyRate);

    virtual uint8_t getConstellationSize() const;
    virtual void setConstellationSize(uint8_t constellationSize);

    virtual ModulationClass getModulationClass() const;
    virtual void setModulationClass(ModulationClass modulationClass);

    virtual uint32_t getFrequency() const;
    virtual void setFrequency(uint32_t frequency);


  public:
    bool operator==(const ModulationType& b) const
    {
        return this->isMandatory == b.isMandatory &&
               this->bandwidth == b.bandwidth &&
               this->codeRate == b.codeRate &&
               this->dataRate == b.dataRate &&
               this->phyRate == b.phyRate &&
               this->constellationSize == b.constellationSize &&
               this->modulationClass == b.modulationClass &&
               this->frequency == b.frequency;
    }
};


}  // namespace simu5g


namespace omnetpp {

inline any_ptr toAnyPtr(const simu5g::ModulationType *p) {if (auto obj = as_cObject(p)) return any_ptr(obj); else return any_ptr(p);}
template<> inline simu5g::ModulationType *fromAnyPtr(any_ptr ptr) { return ptr.get<simu5g::ModulationType>(); }

}  // namespace omnetpp

#endif // ifndef __SIMU5G_MODULATIONTYPE_M_H

