//
// Generated file, do not edit! Created by opp_msgtool 6.3 from simu5g/stack/mac/packet/LteMacSduRequest.msg.
//

#ifndef __SIMU5G_LTEMACSDUREQUEST_M_H
#define __SIMU5G_LTEMACSDUREQUEST_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0603
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif


namespace simu5g {

class LteMacSduRequest;

}  // namespace simu5g

#include "inet/common/INETDefs_m.h" // import inet.common.INETDefs

#include "inet/common/packet/chunk/Chunk_m.h" // import inet.common.packet.chunk.Chunk

#include "simu5g/common/LteCommon_m.h" // import simu5g.common.LteCommon


namespace simu5g {

/**
 * Class generated from <tt>simu5g/stack/mac/packet/LteMacSduRequest.msg:23</tt> by opp_msgtool.
 * <pre>
 * //
 * // This is the message that asks the RLC layer for a new MAC SDU.
 * //
 * class LteMacSduRequest extends inet::FieldsChunk
 * {
 *     unsigned int sduSize;       // size of the requested SDU
 *     chunkLength = inet::B(1); // TODO: size 0
 *     MacNodeId ueId = NODEID_NONE;     // ID of the destination UE associated with the request
 *     LogicalCid lcid = 0;              // Logical Connection identifier associated with the request
 * }
 * </pre>
 */
class LteMacSduRequest : public ::inet::FieldsChunk
{
  protected:
    unsigned int sduSize = 0;
    MacNodeId ueId = NODEID_NONE;
    LogicalCid lcid = 0;

  private:
    void copy(const LteMacSduRequest& other);

  protected:
    bool operator==(const LteMacSduRequest&) = delete;

  public:
    LteMacSduRequest();
    LteMacSduRequest(const LteMacSduRequest& other);
    virtual ~LteMacSduRequest();
    LteMacSduRequest& operator=(const LteMacSduRequest& other);
    virtual LteMacSduRequest *dup() const override {return new LteMacSduRequest(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual unsigned int getSduSize() const;
    virtual void setSduSize(unsigned int sduSize);

    virtual MacNodeId getUeId() const;
    virtual void setUeId(MacNodeId ueId);

    virtual LogicalCid getLcid() const;
    virtual void setLcid(LogicalCid lcid);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const LteMacSduRequest& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, LteMacSduRequest& obj) {obj.parsimUnpack(b);}


}  // namespace simu5g


namespace omnetpp {

template<> inline simu5g::LteMacSduRequest *fromAnyPtr(any_ptr ptr) { return check_and_cast<simu5g::LteMacSduRequest*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __SIMU5G_LTEMACSDUREQUEST_M_H

