//
// Generated file, do not edit! Created by opp_msgtool 6.3 from simu5g/stack/mac/packet/LteMacPdu.msg.
//

#ifndef __SIMU5G_LTEMACPDU_M_H
#define __SIMU5G_LTEMACPDU_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0603
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif


namespace simu5g {

class LteMacPdu;
class MacControlElement;
class MacBsr;

}  // namespace simu5g

#include "inet/common/INETDefs_m.h" // import inet.common.INETDefs

#include "inet/common/packet/chunk/Chunk_m.h" // import inet.common.packet.chunk.Chunk

#include "inet/common/packet/Packet_m.h" // import inet.common.packet.Packet

// cplusplus {{
namespace simu5g {
using namespace omnetpp;
using namespace inet;
} // namespace
// }}


namespace simu5g {

/**
 * Class generated from <tt>simu5g/stack/mac/packet/LteMacPdu.msg:29</tt> by opp_msgtool.
 * <pre>
 * //
 * // This is the MAC message flowing through LTE stack.
 * //
 * class LteMacPdu extends inet::FieldsChunk
 * {
 *     /// ID of the MAC PDU: incrementally set according to the static variable numMacPdus
 *     int64_t macPduId_ = getChunkId();
 * 
 *     // Length of the PDU
 *     int64_t macPduLength_ = 0;
 * 
 *     // List Of MAC SDUs
 *     inet::Packet *sdu[] \@owned \@getter(getSduPtr);
 * 
 *     // List of MAC CEs
 *     MacControlElement *ce[] \@owned;
 * 
 *     unsigned int headerLength = 0;
 *     // need separate macPduId (e.g. for feedback packets) since OMNET PDU id is automatically updated
 *     // whenever a new packet is created, e.g. when this PDU is duplicated
 *     long macPduId = 0;
 * }
 * </pre>
 */
class LteMacPdu : public ::inet::FieldsChunk
{
  protected:
    int64_t macPduId_ = getChunkId();
    int64_t macPduLength_ = 0;
    ::inet::Packet * *sdu = nullptr;
    size_t sdu_arraysize = 0;
    MacControlElement * *ce = nullptr;
    size_t ce_arraysize = 0;
    unsigned int headerLength = 0;
    long macPduId = 0;

  private:
    void copy(const LteMacPdu& other);

  protected:
    bool operator==(const LteMacPdu&) = delete;

  public:
    LteMacPdu();
    LteMacPdu(const LteMacPdu& other);
    virtual ~LteMacPdu();
    LteMacPdu& operator=(const LteMacPdu& other);
    virtual LteMacPdu *dup() const override {return new LteMacPdu(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int64_t getMacPduId_() const;
    virtual void setMacPduId_(int64_t macPduId_);

    virtual int64_t getMacPduLength_() const;
    virtual void setMacPduLength_(int64_t macPduLength_);

    virtual void setSduArraySize(size_t size);
    virtual size_t getSduArraySize() const;
    virtual const ::inet::Packet * getSduPtr(size_t k) const;
    virtual ::inet::Packet * getSduForUpdate(size_t k) { handleChange();return const_cast<::inet::Packet *>(const_cast<LteMacPdu*>(this)->getSduPtr(k));}
    virtual void setSdu(size_t k, ::inet::Packet * sdu);
    virtual ::inet::Packet * removeSdu(size_t k);
    [[deprecated]] ::inet::Packet * dropSdu(size_t k) {return removeSdu(k);}
    virtual void insertSdu(size_t k, ::inet::Packet * sdu);
    [[deprecated]] void insertSdu(::inet::Packet * sdu) {appendSdu(sdu);}
    virtual void appendSdu(::inet::Packet * sdu);
    virtual void eraseSdu(size_t k);

    virtual void setCeArraySize(size_t size);
    virtual size_t getCeArraySize() const;
    virtual const MacControlElement * getCe(size_t k) const;
    virtual MacControlElement * getCeForUpdate(size_t k) { handleChange();return const_cast<MacControlElement *>(const_cast<LteMacPdu*>(this)->getCe(k));}
    virtual void setCe(size_t k, MacControlElement * ce);
    virtual MacControlElement * removeCe(size_t k);
    [[deprecated]] MacControlElement * dropCe(size_t k) {return removeCe(k);}
    virtual void insertCe(size_t k, MacControlElement * ce);
    [[deprecated]] void insertCe(MacControlElement * ce) {appendCe(ce);}
    virtual void appendCe(MacControlElement * ce);
    virtual void eraseCe(size_t k);

    virtual unsigned int getHeaderLength() const;
    virtual void setHeaderLength(unsigned int headerLength);

    virtual long getMacPduId() const;
    virtual void setMacPduId(long macPduId);


  public:
    /**
     * pushSdu() gets ownership of the packet
     * and stores it inside the MAC SDU list
     * in back position
     *
     * @param pkt packet to store
     */
    virtual void pushSdu(Packet *pkt);

    /**
     * popSdu() pops a packet from the front of
     * the SDU list and drops ownership before
     * returning it
     *
     * @return popped packet
     */
    virtual Packet* popSdu();

    /**
     * hasSdu() verifies if there are other
     * SDUs inside the SDU list
     *
     * @return true if the list is not empty, false otherwise
     */
    virtual bool hasSdu() { return sdu_arraysize != 0; }

    const inet::Packet& getSdu(size_t k) const { return *getSduPtr(k); }

    int64_t getByteLength() const { return macPduLength_ + getHeaderLength(); }

    int64_t getBitLength() const { return getByteLength() * 8; }

    /**
     * pushCe() stores a CE inside the
     * MAC CE list in back position
     *
     * @param pkt CE to store
     */
    virtual void pushCe(MacControlElement *ce) { appendCe(ce); }

    /**
     * popCe() pops a CE from the front of
     * the CE list and returns it
     *
     * @return popped CE
     */
    virtual MacControlElement *popCe() {
        MacControlElement *ce = removeCe(0);
        eraseCe(0);
        return ce;
    }

    /**
     * hasCe() verifies if there are other
     * CEs inside the CE list
     *
     * @return true if the list is not empty, false otherwise
     */
    virtual bool hasCe() const { return ce_arraysize != 0; }

    virtual std::string str() const override;
    virtual void forEachChild(cVisitor *v) override;

    long getId() const { return macPduId_; }
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const LteMacPdu& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, LteMacPdu& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>simu5g/stack/mac/packet/LteMacPdu.msg:139</tt> by opp_msgtool.
 * <pre>
 * //
 * // Mac Control Element
 * //
 * class MacControlElement extends cObject
 * {
 *     double timestamp;
 * }
 * </pre>
 */
class MacControlElement : public ::omnetpp::cObject
{
  protected:
    double timestamp = 0;

  private:
    void copy(const MacControlElement& other);

  protected:
    bool operator==(const MacControlElement&) = delete;

  public:
    MacControlElement();
    MacControlElement(const MacControlElement& other);
    virtual ~MacControlElement();
    MacControlElement& operator=(const MacControlElement& other);
    virtual MacControlElement *dup() const override {return new MacControlElement(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual double getTimestamp() const;
    virtual void setTimestamp(double timestamp);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const MacControlElement& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, MacControlElement& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>simu5g/stack/mac/packet/LteMacPdu.msg:147</tt> by opp_msgtool.
 * <pre>
 * //
 * // Mac Buffer Status Report
 * //
 * class MacBsr extends MacControlElement
 * {
 *     int size;
 * }
 * </pre>
 */
class MacBsr : public ::simu5g::MacControlElement
{
  protected:
    int size = 0;

  private:
    void copy(const MacBsr& other);

  protected:
    bool operator==(const MacBsr&) = delete;

  public:
    MacBsr();
    MacBsr(const MacBsr& other);
    virtual ~MacBsr();
    MacBsr& operator=(const MacBsr& other);
    virtual MacBsr *dup() const override {return new MacBsr(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getSize() const;
    virtual void setSize(int size);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const MacBsr& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, MacBsr& obj) {obj.parsimUnpack(b);}


}  // namespace simu5g


namespace omnetpp {

template<> inline simu5g::LteMacPdu *fromAnyPtr(any_ptr ptr) { return check_and_cast<simu5g::LteMacPdu*>(ptr.get<cObject>()); }
template<> inline simu5g::MacControlElement *fromAnyPtr(any_ptr ptr) { return check_and_cast<simu5g::MacControlElement*>(ptr.get<cObject>()); }
template<> inline simu5g::MacBsr *fromAnyPtr(any_ptr ptr) { return check_and_cast<simu5g::MacBsr*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __SIMU5G_LTEMACPDU_M_H

