//
// Generated file, do not edit! Created by opp_msgtool 6.3 from simu5g/stack/mac/packet/LteSchedulingGrant.msg.
//

#ifndef __SIMU5G_LTESCHEDULINGGRANT_M_H
#define __SIMU5G_LTESCHEDULINGGRANT_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0603
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif


namespace simu5g {

class LteSchedulingGrant;

}  // namespace simu5g

#include "inet/common/INETDefs_m.h" // import inet.common.INETDefs

#include "inet/common/packet/chunk/Chunk_m.h" // import inet.common.packet.chunk.Chunk

#include "simu5g/common/LteCommonEnum_m.h" // import simu5g.common.LteCommonEnum

#include "simu5g/common/LteCommon_m.h" // import simu5g.common.LteCommon

#include "simu5g/stack/mac/amc/UserTxParams_m.h" // import simu5g.stack.mac.amc.UserTxParams


namespace simu5g {

/**
 * Class generated from <tt>simu5g/stack/mac/packet/LteSchedulingGrant.msg:25</tt> by opp_msgtool.
 * <pre>
 * //
 * // TODO generated message class
 * //
 * class LteSchedulingGrant extends inet::FieldsChunk
 * {
 *     chunkLength = inet::B(1); // TODO: size 0
 *     bool periodic;
 *     unsigned int period;
 *     unsigned int expiration;
 *     unsigned int totalGrantedBlocks;    // blocks granted on all Remotes, all Bands
 *     unsigned int codewords;    // number of codewords
 *     unsigned int grantedCwBytes[MAX_CODEWORDS];    // granted bytes per codeword
 *     const UserTxParams *userTxParams \@owned \@allowReplace = nullptr;
 *     Direction direction;    // Traffic Direction
 *     unsigned int grantId = getChunkId();         // Grant identifier
 * }
 * </pre>
 */
class LteSchedulingGrant : public ::inet::FieldsChunk
{
  protected:
    bool periodic = false;
    unsigned int period = 0;
    unsigned int expiration = 0;
    unsigned int totalGrantedBlocks = 0;
    unsigned int codewords = 0;
    unsigned int grantedCwBytes[MAX_CODEWORDS] = {0};
    const UserTxParams * userTxParams = nullptr;
    Direction direction = static_cast<simu5g::Direction>(-1);
    unsigned int grantId = getChunkId();

  private:
    void copy(const LteSchedulingGrant& other);

  protected:
    bool operator==(const LteSchedulingGrant&) = delete;

  public:
    LteSchedulingGrant();
    LteSchedulingGrant(const LteSchedulingGrant& other);
    virtual ~LteSchedulingGrant();
    LteSchedulingGrant& operator=(const LteSchedulingGrant& other);
    virtual LteSchedulingGrant *dup() const override {return new LteSchedulingGrant(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual bool getPeriodic() const;
    virtual void setPeriodic(bool periodic);

    virtual unsigned int getPeriod() const;
    virtual void setPeriod(unsigned int period);

    virtual unsigned int getExpiration() const;
    virtual void setExpiration(unsigned int expiration);

    virtual unsigned int getTotalGrantedBlocks() const;
    virtual void setTotalGrantedBlocks(unsigned int totalGrantedBlocks);

    virtual unsigned int getCodewords() const;
    virtual void setCodewords(unsigned int codewords);

    virtual size_t getGrantedCwBytesArraySize() const;
    virtual unsigned int getGrantedCwBytes(size_t k) const;
    virtual void setGrantedCwBytes(size_t k, unsigned int grantedCwBytes);

    virtual const UserTxParams * getUserTxParams() const;
    virtual void setUserTxParams(const UserTxParams * userTxParams);
    virtual UserTxParams * removeUserTxParams();
    [[deprecated]] UserTxParams * dropUserTxParams() {return removeUserTxParams();}

    virtual Direction getDirection() const;
    virtual void setDirection(Direction direction);

    virtual unsigned int getGrantId() const;
    virtual void setGrantId(unsigned int grantId);


  protected:
    RbMap grantedBlocks;

  public:
    const unsigned int getBlocks(Remote antenna, Band b) const { return grantedBlocks.at(antenna).at(b); }
    void setBlocks(Remote antenna, Band b, unsigned int blocks) { grantedBlocks[antenna][b] = blocks; }
    const RbMap& getGrantedBlocks() const { return grantedBlocks; }
    void setGrantedBlocks(const RbMap& rbMap) { handleChange(); grantedBlocks = rbMap; }
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const LteSchedulingGrant& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, LteSchedulingGrant& obj) {obj.parsimUnpack(b);}


}  // namespace simu5g


namespace omnetpp {

template<> inline simu5g::LteSchedulingGrant *fromAnyPtr(any_ptr ptr) { return check_and_cast<simu5g::LteSchedulingGrant*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __SIMU5G_LTESCHEDULINGGRANT_M_H

