//
// Generated file, do not edit! Created by opp_msgtool 6.3 from simu5g/stack/rlc/LteRlcDefs.msg.
//

#ifndef __SIMU5G_LTERLCDEFS_M_H
#define __SIMU5G_LTERLCDEFS_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0603
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif


namespace simu5g {

struct RlcFragDesc;
struct RlcWindowDesc;
struct MrwDesc;
struct FramingInfo;
struct RlcUmRxWindowDesc;

}  // namespace simu5g

#include "simu5g/common/LteControlInfo_m.h" // import simu5g.common.LteControlInfo

#include "simu5g/stack/rlc/packet/LteRlcPdu_m.h" // import simu5g.stack.rlc.packet.LteRlcPdu

#include "simu5g/stack/rlc/packet/LteRlcSdu_m.h" // import simu5g.stack.rlc.packet.LteRlcSdu

// cplusplus {{
#include "simu5g/common/LteControlInfo.h"
// }}


namespace simu5g {

/**
 * Enum generated from <tt>simu5g/stack/rlc/LteRlcDefs.msg:26</tt> by opp_msgtool.
 * <pre>
 * //
 * // LTE RLC AM Types
 * //
 * enum LteAmType
 * {
 *     // Data packet
 *     DATA = 0;
 *     // ****** control packets ********
 *     // ACK
 *     ACK = 1;
 *     // Move Receiver Window
 *     MRW = 2;
 *     // Move Receiver Window ACK
 *     MRW_ACK = 3;
 *     // BITMAP
 *     // BITMAP = 4;
 * }
 * 
 * //
 * // RLC AM Window descriptor
 * //
 * </pre>
 */
enum LteAmType {
    DATA = 0,
    ACK = 1,
    MRW = 2,
    MRW_ACK = 3
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const LteAmType& e) { b->pack(static_cast<int>(e)); }
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, LteAmType& e) { int n; b->unpack(n); e = static_cast<LteAmType>(n); }

/**
 * Struct generated from simu5g/stack/rlc/LteRlcDefs.msg:45 by opp_msgtool.
 */
struct RlcFragDesc
{
    RlcFragDesc();
    int sduSize_ = 0;
    int fragUnit_ = 0;
    int totalFragments_ = 0;
    int fragCounter_ = 0;
    int firstSn_ = 0;

  public:
    /*
     * Configures the fragmentation descriptor for working on an SDU of size sduSize
     */
    void startFragmentation(unsigned int sduSize, unsigned int firstFragment)
    {
        totalFragments_ = ceil((double)sduSize / (double)fragUnit_);
        fragCounter_ = 0;
        firstSn_ = firstFragment;
    }

    /*
     * resets the fragmentation descriptor for working on an SDU of size sduSize - frag unit is left untouched.
     */
    void resetFragmentation()
    {
        sduSize_ = 0;
        totalFragments_ = 0;
        fragCounter_ = 0;
        firstSn_ = 0;
    }

    /*
     * adds a fragment to the created ones. if the last is added, returns true
     */
    bool addFragment()
    {
        fragCounter_++;
        return fragCounter_ >= totalFragments_;
    }
};

// helpers for local use
void __doPacking(omnetpp::cCommBuffer *b, const RlcFragDesc& a);
void __doUnpacking(omnetpp::cCommBuffer *b, RlcFragDesc& a);

inline void doParsimPacking(omnetpp::cCommBuffer *b, const RlcFragDesc& obj) { __doPacking(b, obj); }
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, RlcFragDesc& obj) { __doUnpacking(b, obj); }

/**
 * Struct generated from simu5g/stack/rlc/LteRlcDefs.msg:96 by opp_msgtool.
 */
struct RlcWindowDesc
{
    RlcWindowDesc();
    unsigned int firstSeqNum_ = 0;
    unsigned int seqNum_ = 0;
    unsigned int windowSize_ = 0;
};

// helpers for local use
void __doPacking(omnetpp::cCommBuffer *b, const RlcWindowDesc& a);
void __doUnpacking(omnetpp::cCommBuffer *b, RlcWindowDesc& a);

inline void doParsimPacking(omnetpp::cCommBuffer *b, const RlcWindowDesc& obj) { __doPacking(b, obj); }
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, RlcWindowDesc& obj) { __doUnpacking(b, obj); }

/**
 * Struct generated from simu5g/stack/rlc/LteRlcDefs.msg:109 by opp_msgtool.
 */
struct MrwDesc
{
    MrwDesc();
    unsigned int mrwSeqNum_ = 0;
    unsigned int lastMrw_ = 0;
};

// helpers for local use
void __doPacking(omnetpp::cCommBuffer *b, const MrwDesc& a);
void __doUnpacking(omnetpp::cCommBuffer *b, MrwDesc& a);

inline void doParsimPacking(omnetpp::cCommBuffer *b, const MrwDesc& obj) { __doPacking(b, obj); }
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, MrwDesc& obj) { __doUnpacking(b, obj); }

/**
 * Enum generated from <tt>simu5g/stack/rlc/LteRlcDefs.msg:117</tt> by opp_msgtool.
 * <pre>
 * enum RlcAmTimerType
 * {
 *     PDU_T = 0;
 *     MRW_T = 1;
 *     BUFFER_T = 2;
 *     BUFFERSTATUS_T = 3;
 * }
 * 
 * //
 * // RLC Data PDU
 * //
 * </pre>
 */
enum RlcAmTimerType {
    PDU_T = 0,
    MRW_T = 1,
    BUFFER_T = 2,
    BUFFERSTATUS_T = 3
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const RlcAmTimerType& e) { b->pack(static_cast<int>(e)); }
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, RlcAmTimerType& e) { int n; b->unpack(n); e = static_cast<RlcAmTimerType>(n); }

/**
 * Struct generated from simu5g/stack/rlc/LteRlcDefs.msg:134 by opp_msgtool.
 */
struct FramingInfo
{
    FramingInfo();
    bool firstIsFragment = false;
    bool lastIsFragment = false;

    short toValue() { return (firstIsFragment ? 2 : 0) | (lastIsFragment ? 1 : 0); }
};

// helpers for local use
void __doPacking(omnetpp::cCommBuffer *b, const FramingInfo& a);
void __doUnpacking(omnetpp::cCommBuffer *b, FramingInfo& a);

inline void doParsimPacking(omnetpp::cCommBuffer *b, const FramingInfo& obj) { __doPacking(b, obj); }
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, FramingInfo& obj) { __doUnpacking(b, obj); }

/**
 * Struct generated from simu5g/stack/rlc/LteRlcDefs.msg:147 by opp_msgtool.
 */
struct RlcUmRxWindowDesc
{
    RlcUmRxWindowDesc();
    unsigned int firstSno_ = 0;
    unsigned int firstSnoForReordering_ = 0;
    unsigned int reorderingSno_ = 0;
    unsigned int highestReceivedSno_ = 0;
    unsigned int windowSize_ = 0;

    void clear(unsigned int i = 0)
    {
        firstSno_ = i;
        firstSnoForReordering_ = i;
        reorderingSno_ = i;
        highestReceivedSno_ = i;
    }
};

// helpers for local use
void __doPacking(omnetpp::cCommBuffer *b, const RlcUmRxWindowDesc& a);
void __doUnpacking(omnetpp::cCommBuffer *b, RlcUmRxWindowDesc& a);

inline void doParsimPacking(omnetpp::cCommBuffer *b, const RlcUmRxWindowDesc& obj) { __doPacking(b, obj); }
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, RlcUmRxWindowDesc& obj) { __doUnpacking(b, obj); }

/**
 * Enum generated from <tt>simu5g/stack/rlc/LteRlcDefs.msg:171</tt> by opp_msgtool.
 * <pre>
 * enum RlcUmTimerType
 * {
 *     REORDERING_T = 0;
 * }
 * </pre>
 */
enum RlcUmTimerType {
    REORDERING_T = 0
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const RlcUmTimerType& e) { b->pack(static_cast<int>(e)); }
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, RlcUmTimerType& e) { int n; b->unpack(n); e = static_cast<RlcUmTimerType>(n); }


}  // namespace simu5g


namespace omnetpp {

inline any_ptr toAnyPtr(const simu5g::RlcFragDesc *p) {return any_ptr(p);}
template<> inline simu5g::RlcFragDesc *fromAnyPtr(any_ptr ptr) { return ptr.get<simu5g::RlcFragDesc>(); }
inline any_ptr toAnyPtr(const simu5g::RlcWindowDesc *p) {return any_ptr(p);}
template<> inline simu5g::RlcWindowDesc *fromAnyPtr(any_ptr ptr) { return ptr.get<simu5g::RlcWindowDesc>(); }
inline any_ptr toAnyPtr(const simu5g::MrwDesc *p) {return any_ptr(p);}
template<> inline simu5g::MrwDesc *fromAnyPtr(any_ptr ptr) { return ptr.get<simu5g::MrwDesc>(); }
inline any_ptr toAnyPtr(const simu5g::FramingInfo *p) {return any_ptr(p);}
template<> inline simu5g::FramingInfo *fromAnyPtr(any_ptr ptr) { return ptr.get<simu5g::FramingInfo>(); }
inline any_ptr toAnyPtr(const simu5g::RlcUmRxWindowDesc *p) {return any_ptr(p);}
template<> inline simu5g::RlcUmRxWindowDesc *fromAnyPtr(any_ptr ptr) { return ptr.get<simu5g::RlcUmRxWindowDesc>(); }

}  // namespace omnetpp

#endif // ifndef __SIMU5G_LTERLCDEFS_M_H

