//
// Generated file, do not edit! Created by opp_msgtool 6.3 from simu5g/stack/mac/amc/UserTxParams.msg.
//

#ifndef __SIMU5G_USERTXPARAMS_M_H
#define __SIMU5G_USERTXPARAMS_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0603
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif


namespace simu5g {

class UserTxParams;

}  // namespace simu5g

#include "simu5g/common/LteCommonEnum_m.h" // import simu5g.common.LteCommonEnum

#include "simu5g/common/LteCommon_m.h" // import simu5g.common.LteCommon

// cplusplus {{
#include "simu5g/stack/mac/amc/LteMcs.h"
// }}


namespace simu5g {

/**
 * Class generated from <tt>simu5g/stack/mac/amc/UserTxParams.msg:32</tt> by opp_msgtool.
 * <pre>
 * //
 * // \@class UserTxParams
 * //
 * // This class specifies the transmission mode and the resources
 * // used by a user for the transmission.
 * // The class also contains the RI, CQI, PMI actually used for transmission.
 * //
 * // UserTxParams are set by the AMC Pilot.
 * //
 * class UserTxParams
 * {
 *     TxMode txMode \@getter(readTxMode) \@setter(writeTxMode) = SINGLE_ANTENNA_PORT0; // tx mode to use
 * 
 *     Rank ri \@getter(readRank) \@setter(writeRank) = NORANK;       // RI
 * 
 *     Cqi cqiVector[] \@custom = CQI_INIT_VALUES; // vector with as many elements as there are cw: therefore it contains wb cqi
 * 
 *     Pmi pmi \@getter(readPmi) \@setter(writePmi) = NOPMI;       // WB pmi
 * 
 *     // std::set<Band> allowedBands_;     // bands on which the user can transmit
 *     // TODO make as visible
 * 
 *     bool valid \@getter(isValid) = false; // indicates whether the user info is set
 * 
 *     //! set of Remote Antennas in use for transmission  (DAS support)
 *     // std::set<Remote> antennaSet_;
 *     // TODO make as visible
 * }
 * </pre>
 */
class UserTxParams
{
  protected:
    TxMode txMode = SINGLE_ANTENNA_PORT0;
    Rank ri = NORANK;
    Pmi pmi = NOPMI;
    bool valid = false;

  private:
    void copy(const UserTxParams& other);

  protected:
    bool operator==(const UserTxParams&) = delete;

  public:
    UserTxParams();
    UserTxParams(const UserTxParams& other);
    virtual ~UserTxParams();
    UserTxParams& operator=(const UserTxParams& other);
    virtual void parsimPack(omnetpp::cCommBuffer *b) const;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b);

    virtual TxMode readTxMode() const;
    virtual void writeTxMode(TxMode txMode);

    virtual Rank readRank() const;
    virtual void writeRank(Rank ri);

    virtual Pmi readPmi() const;
    virtual void writePmi(Pmi pmi);

    virtual bool isValid() const;
    virtual void setValid(bool valid);


  protected:
    static std::vector<Cqi> CQI_INIT_VALUES;

    std::vector<Cqi> cqiVector;

    std::set<Band> allowedBands_;     // bands on which the user can transmit

    //! set of Remote Antennas in use for transmission  (DAS support)
    std::set<Remote> antennaSet_;

  public:
    UserTxParams* dup() const { return new UserTxParams(*this); }
    size_t getCqiVectorArraySize() const { return cqiVector.size(); }
    void setCqiVectorArraySize(size_t size) { cqiVector.resize(size); }
    Cqi getCqiVector(size_t k) const { return cqiVector.at(k); } 
    void setCqiVector(size_t k, Cqi cqi) { cqiVector.at(k) = cqi; }
    void eraseCqiVector(size_t k) { cqiVector.clear(); }

    //! Get the per-codeword CQIs.
    const std::vector<Cqi>& readCqiVector() const { return cqiVector; }

    //! Set the per-codeword CQIs.
    void writeCqi(const std::vector<Cqi>& cqi) { cqiVector = cqi; }

    /** Get the modulation of the codeword. This function does not check if codeword is set.
     *  @param cw The codeword.
     *  @return The modulation.
     */
    LteMod getCwModulation(Codeword cw) const { return cqiTable[cqiVector.at(cw)].mod_; }

    /** Get the nominal code rate given the codeword. This function does not check if codeword is set.
     *  @param cw The codeword.
     *  @return The nominal code rate.
     */
    double getCwRate(Codeword cw) const { return cqiTable[cqiVector.at(cw)].rate_; }

    //! Get the assigned band vector.
    const std::set<Band>& readBands() const
    {
        return allowedBands_;
    }

    //! Get the remote antenna set - DAS
    const std::set<Remote>& readAntennaSet() const
    {
        return antennaSet_;
    }

    //! Set the remote antenna set - DAS
    void writeAntennas(const std::set<Remote>& antennas)
    {
        antennaSet_ = antennas;
    }

    //! Get the assigned band vector.
    void writeBands(const std::set<Band>& bands)
    {
        allowedBands_ = bands;
    }

    /** Gives the number of layers for each codeword.
     *  @return A vector containing the number of layers per codeword.
     */
    std::vector<unsigned char> getLayers() const
    {
        return cwMapping(txMode, ri, ri);
    }

    //! Reset to default values.
    void restoreDefaultValues()
    {
        allowedBands_.clear();

        txMode = SINGLE_ANTENNA_PORT0;
        ri = NORANK;
        pmi = NOPMI;
        cqiVector = CQI_INIT_VALUES;

        valid = false;
        antennaSet_.clear();
        // by default the system works with the MACRO antenna configured on all terminals
        antennaSet_.insert(MACRO);
    }

    /** Print debug information - FOR DEBUG ONLY
     *  @param s The name of the invoking function.
     */
    void print(const char *s) const;
};


}  // namespace simu5g


namespace omnetpp {

inline any_ptr toAnyPtr(const simu5g::UserTxParams *p) {if (auto obj = as_cObject(p)) return any_ptr(obj); else return any_ptr(p);}
template<> inline simu5g::UserTxParams *fromAnyPtr(any_ptr ptr) { return ptr.get<simu5g::UserTxParams>(); }

}  // namespace omnetpp

#endif // ifndef __SIMU5G_USERTXPARAMS_M_H

