//
// Generated file, do not edit! Created by opp_msgtool 6.3 from simu5g/stack/compManager/compManagerProportional/X2CompProportionalRequestIE.msg.
//

#ifndef __SIMU5G_X2COMPPROPORTIONALREQUESTIE_M_H
#define __SIMU5G_X2COMPPROPORTIONALREQUESTIE_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0603
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif


namespace simu5g {

class X2CompProportionalRequestIE;

}  // namespace simu5g

#include "simu5g/stack/compManager/X2CompRequestIE_m.h" // import simu5g.stack.compManager.X2CompRequestIE


namespace simu5g {

/**
 * Class generated from <tt>simu5g/stack/compManager/compManagerProportional/X2CompProportionalRequestIE.msg:20</tt> by opp_msgtool.
 * <pre>
 * //
 * // X2CompProportionalRequestIE
 * //
 * class X2CompProportionalRequestIE extends X2CompRequestIE
 * {
 *     // number of "ideally" required blocks to satisfy the queue of all UEs
 *     uint32_t numBlocks;
 * 
 *     type = COMP_PROP_REQUEST_IE;
 *     length = sizeof(uint32_t);
 * }
 * </pre>
 */
class X2CompProportionalRequestIE : public ::simu5g::X2CompRequestIE
{
  protected:
    uint32_t numBlocks = 0;

  private:
    void copy(const X2CompProportionalRequestIE& other);

  protected:
    bool operator==(const X2CompProportionalRequestIE&) = delete;

  public:
    X2CompProportionalRequestIE();
    X2CompProportionalRequestIE(const X2CompProportionalRequestIE& other);
    virtual ~X2CompProportionalRequestIE();
    X2CompProportionalRequestIE& operator=(const X2CompProportionalRequestIE& other);
    virtual X2CompProportionalRequestIE *dup() const override {return new X2CompProportionalRequestIE(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual uint32_t getNumBlocks() const;
    virtual void setNumBlocks(uint32_t numBlocks);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const X2CompProportionalRequestIE& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, X2CompProportionalRequestIE& obj) {obj.parsimUnpack(b);}


}  // namespace simu5g


namespace omnetpp {

template<> inline simu5g::X2CompProportionalRequestIE *fromAnyPtr(any_ptr ptr) { return check_and_cast<simu5g::X2CompProportionalRequestIE*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __SIMU5G_X2COMPPROPORTIONALREQUESTIE_M_H

