//
// Generated file, do not edit! Created by opp_msgtool 6.3 from simu5g/stack/compManager/compManagerProportional/X2CompProportionalReplyIE.msg.
//

#ifndef __SIMU5G_X2COMPPROPORTIONALREPLYIE_M_H
#define __SIMU5G_X2COMPPROPORTIONALREPLYIE_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0603
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif


namespace simu5g {

class X2CompProportionalReplyIE;

}  // namespace simu5g

// cplusplus {{
#include <vector>
// }}

#include "simu5g/stack/compManager/X2CompReplyIE_m.h" // import simu5g.stack.compManager.X2CompReplyIE


namespace simu5g {

/**
 * Enum generated from <tt>simu5g/stack/compManager/compManagerProportional/X2CompProportionalReplyIE.msg:21</tt> by opp_msgtool.
 * <pre>
 * enum CompRbStatus
 * {
 *     AVAILABLE_RB = 0;
 *     NOT_AVAILABLE_RB = 1;
 * }
 * </pre>
 */
enum CompRbStatus {
    AVAILABLE_RB = 0,
    NOT_AVAILABLE_RB = 1
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const CompRbStatus& e) { b->pack(static_cast<int>(e)); }
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, CompRbStatus& e) { int n; b->unpack(n); e = static_cast<CompRbStatus>(n); }

/**
 * Class generated from <tt>simu5g/stack/compManager/compManagerProportional/X2CompProportionalReplyIE.msg:30</tt> by opp_msgtool.
 * <pre>
 * //
 * // X2CompProportionalReplyIE
 * //
 * class X2CompProportionalReplyIE extends X2CompReplyIE
 * {
 *     length = sizeof(uint32_t);    // Required to store the length of the map
 *     type = COMP_PROP_REPLY_IE;
 *     CompRbStatus allowedBlocksMap[];
 *     //std::vector<CompRbStatus> allowedBlocksMap_;
 * }
 * </pre>
 */
class X2CompProportionalReplyIE : public ::simu5g::X2CompReplyIE
{
  protected:
    CompRbStatus *allowedBlocksMap = nullptr;
    size_t allowedBlocksMap_arraysize = 0;

  private:
    void copy(const X2CompProportionalReplyIE& other);

  protected:
    bool operator==(const X2CompProportionalReplyIE&) = delete;

  public:
    X2CompProportionalReplyIE();
    X2CompProportionalReplyIE(const X2CompProportionalReplyIE& other);
    virtual ~X2CompProportionalReplyIE();
    X2CompProportionalReplyIE& operator=(const X2CompProportionalReplyIE& other);
    virtual X2CompProportionalReplyIE *dup() const override {return new X2CompProportionalReplyIE(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual void setAllowedBlocksMapArraySize(size_t size);
    virtual size_t getAllowedBlocksMapArraySize() const;
    virtual CompRbStatus getAllowedBlocksMap(size_t k) const;
    virtual void setAllowedBlocksMap(size_t k, CompRbStatus allowedBlocksMap);
    virtual void insertAllowedBlocksMap(size_t k, CompRbStatus allowedBlocksMap);
    [[deprecated]] void insertAllowedBlocksMap(CompRbStatus allowedBlocksMap) {appendAllowedBlocksMap(allowedBlocksMap);}
    virtual void appendAllowedBlocksMap(CompRbStatus allowedBlocksMap);
    virtual void eraseAllowedBlocksMap(size_t k);


  public:
    void setAllowedBlocksMap(std::vector<CompRbStatus>& map);
    const std::vector<CompRbStatus> getAllowedBlocksMap() const;
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const X2CompProportionalReplyIE& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, X2CompProportionalReplyIE& obj) {obj.parsimUnpack(b);}


}  // namespace simu5g


namespace omnetpp {

template<> inline simu5g::X2CompProportionalReplyIE *fromAnyPtr(any_ptr ptr) { return check_and_cast<simu5g::X2CompProportionalReplyIE*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __SIMU5G_X2COMPPROPORTIONALREPLYIE_M_H

