//
// Generated file, do not edit! Created by opp_msgtool 6.3 from simu5g/mec/platform/MecPackets.msg.
//

#ifndef __SIMU5G_MECPACKETS_M_H
#define __SIMU5G_MECPACKETS_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0603
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif


namespace simu5g {

class MecPacket;

}  // namespace simu5g

#include "inet/common/INETDefs_m.h" // import inet.common.INETDefs

#include "inet/common/packet/chunk/Chunk_m.h" // import inet.common.packet.chunk.Chunk


namespace simu5g {

/**
 * Class generated from <tt>simu5g/mec/platform/MecPackets.msg:17</tt> by opp_msgtool.
 * <pre>
 * class MecPacket extends inet::FieldsChunk
 * {
 *     unsigned int sno;
 *     simtime_t timestamp;
 *     //type of message
 *     string type;
 * }
 * </pre>
 */
class MecPacket : public ::inet::FieldsChunk
{
  protected:
    unsigned int sno = 0;
    ::omnetpp::simtime_t timestamp = SIMTIME_ZERO;
    ::omnetpp::opp_string type;

  private:
    void copy(const MecPacket& other);

  protected:
    bool operator==(const MecPacket&) = delete;

  public:
    MecPacket();
    MecPacket(const MecPacket& other);
    virtual ~MecPacket();
    MecPacket& operator=(const MecPacket& other);
    virtual MecPacket *dup() const override {return new MecPacket(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual unsigned int getSno() const;
    virtual void setSno(unsigned int sno);

    virtual ::omnetpp::simtime_t getTimestamp() const;
    virtual void setTimestamp(::omnetpp::simtime_t timestamp);

    virtual const char * getType() const;
    virtual void setType(const char * type);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const MecPacket& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, MecPacket& obj) {obj.parsimUnpack(b);}


}  // namespace simu5g


namespace omnetpp {

template<> inline simu5g::MecPacket *fromAnyPtr(any_ptr ptr) { return check_and_cast<simu5g::MecPacket*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __SIMU5G_MECPACKETS_M_H

