//
// Generated file, do not edit! Created by opp_msgtool 6.3 from simu5g/stack/handoverManager/X2HandoverCommandIE.msg.
//

#ifndef __SIMU5G_X2HANDOVERCOMMANDIE_M_H
#define __SIMU5G_X2HANDOVERCOMMANDIE_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0603
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif


namespace simu5g {

class X2HandoverCommandIE;

}  // namespace simu5g

#include "simu5g/x2/packet/X2InformationElement_m.h" // import simu5g.x2.packet.X2InformationElement

#include "simu5g/common/LteCommon_m.h" // import simu5g.common.LteCommon


namespace simu5g {

/**
 * Class generated from <tt>simu5g/stack/handoverManager/X2HandoverCommandIE.msg:22</tt> by opp_msgtool.
 * <pre>
 * //
 * // X2HandoverCommandIE
 * //
 * class X2HandoverCommandIE extends X2InformationElement
 * {
 *     type = X2_HANDOVER_CMD_IE;
 *     length = sizeof(MacNodeId) + sizeof(uint8_t);
 *     bool startHandover \@getter(isStartHandover) = false;
 *     MacNodeId ueId = NODEID_NONE;      // ID of the user performing the handover
 * }
 * </pre>
 */
class X2HandoverCommandIE : public ::simu5g::X2InformationElement
{
  protected:
    bool startHandover = false;
    MacNodeId ueId = NODEID_NONE;

  private:
    void copy(const X2HandoverCommandIE& other);

  protected:
    bool operator==(const X2HandoverCommandIE&) = delete;

  public:
    X2HandoverCommandIE();
    X2HandoverCommandIE(const X2HandoverCommandIE& other);
    virtual ~X2HandoverCommandIE();
    X2HandoverCommandIE& operator=(const X2HandoverCommandIE& other);
    virtual X2HandoverCommandIE *dup() const override {return new X2HandoverCommandIE(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual bool isStartHandover() const;
    virtual void setStartHandover(bool startHandover);

    virtual MacNodeId getUeId() const;
    virtual void setUeId(MacNodeId ueId);


  public:
    void setStartHandover() { startHandover = true; }
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const X2HandoverCommandIE& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, X2HandoverCommandIE& obj) {obj.parsimUnpack(b);}


}  // namespace simu5g


namespace omnetpp {

template<> inline simu5g::X2HandoverCommandIE *fromAnyPtr(any_ptr ptr) { return check_and_cast<simu5g::X2HandoverCommandIE*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __SIMU5G_X2HANDOVERCOMMANDIE_M_H

