//
// Generated file, do not edit! Created by opp_msgtool 6.3 from simu5g/stack/pdcp/packet/LtePdcpPdu.msg.
//

#ifndef __SIMU5G_LTEPDCPPDU_M_H
#define __SIMU5G_LTEPDCPPDU_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0603
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif


namespace simu5g {

class LtePdcpHeader;

}  // namespace simu5g

#include "inet/common/packet/chunk/Chunk_m.h" // import inet.common.packet.chunk.Chunk


namespace simu5g {

/**
 * Class generated from <tt>simu5g/stack/pdcp/packet/LtePdcpPdu.msg:20</tt> by opp_msgtool.
 * <pre>
 * //
 * // This is the PDCP message flowing through LTE stack.
 * //
 * class LtePdcpHeader extends inet::FieldsChunk
 * {
 *     chunkLength = inet::B(1); // TODO: size 0
 * }
 * </pre>
 */
class LtePdcpHeader : public ::inet::FieldsChunk
{
  protected:

  private:
    void copy(const LtePdcpHeader& other);

  protected:
    bool operator==(const LtePdcpHeader&) = delete;

  public:
    LtePdcpHeader();
    LtePdcpHeader(const LtePdcpHeader& other);
    virtual ~LtePdcpHeader();
    LtePdcpHeader& operator=(const LtePdcpHeader& other);
    virtual LtePdcpHeader *dup() const override {return new LtePdcpHeader(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const LtePdcpHeader& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, LtePdcpHeader& obj) {obj.parsimUnpack(b);}


}  // namespace simu5g


namespace omnetpp {

template<> inline simu5g::LtePdcpHeader *fromAnyPtr(any_ptr ptr) { return check_and_cast<simu5g::LtePdcpHeader*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __SIMU5G_LTEPDCPPDU_M_H

