//
// Generated file, do not edit! Created by opp_msgtool 6.3 from simu5g/stack/rlc/packet/LteRlcDataPdu.msg.
//

#ifndef __SIMU5G_LTERLCDATAPDU_M_H
#define __SIMU5G_LTERLCDATAPDU_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0603
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif


namespace simu5g {

class LteRlcDataPdu;
class LteRlcUmDataPdu;
class LteRlcAmDataPdu;

}  // namespace simu5g

#include "inet/common/INETDefs_m.h" // import inet.common.INETDefs

#include "inet/common/packet/chunk/Chunk_m.h" // import inet.common.packet.chunk.Chunk

#include "inet/common/packet/Packet_m.h" // import inet.common.packet.Packet

#include "simu5g/stack/rlc/LteRlcDefs_m.h" // import simu5g.stack.rlc.LteRlcDefs


namespace simu5g {

/**
 * Class generated from <tt>simu5g/stack/rlc/packet/LteRlcDataPdu.msg:39</tt> by opp_msgtool.
 * <pre>
 * class LteRlcDataPdu extends inet::FieldsChunk
 * {
 *     chunkLength = inet::b(1);
 * 
 *     // Length of the PDU
 *     int64_t rlcPduLength = 0;
 * 
 *     inet::Packet *sdu[] \@sizeGetter(getNumSdu) \@owned;
 *     size_t sduSize[];
 * 
 *     // Sequence number of the PDU
 *     unsigned int pduSequenceNumber = 0;
 * 
 *     // define the segmentation info for the PDU
 *     FramingInfo framingInfo;
 * }
 * </pre>
 */
class LteRlcDataPdu : public ::inet::FieldsChunk
{
  protected:
    int64_t rlcPduLength = 0;
    ::inet::Packet * *sdu = nullptr;
    size_t sdu_arraysize = 0;
    ::size_t *sduSize = nullptr;
    size_t sduSize_arraysize = 0;
    unsigned int pduSequenceNumber = 0;
    FramingInfo framingInfo;

  private:
    void copy(const LteRlcDataPdu& other);

  protected:
    bool operator==(const LteRlcDataPdu&) = delete;

  public:
    LteRlcDataPdu();
    LteRlcDataPdu(const LteRlcDataPdu& other);
    virtual ~LteRlcDataPdu();
    LteRlcDataPdu& operator=(const LteRlcDataPdu& other);
    virtual LteRlcDataPdu *dup() const override {return new LteRlcDataPdu(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int64_t getRlcPduLength() const;
    virtual void setRlcPduLength(int64_t rlcPduLength);

    virtual void setSduArraySize(size_t size);
    virtual size_t getNumSdu() const;
    virtual const ::inet::Packet * getSdu(size_t k) const;
    virtual ::inet::Packet * getSduForUpdate(size_t k) { handleChange();return const_cast<::inet::Packet *>(const_cast<LteRlcDataPdu*>(this)->getSdu(k));}
    virtual void setSdu(size_t k, ::inet::Packet * sdu);
    virtual ::inet::Packet * removeSdu(size_t k);
    [[deprecated]] ::inet::Packet * dropSdu(size_t k) {return removeSdu(k);}
    virtual void insertSdu(size_t k, ::inet::Packet * sdu);
    [[deprecated]] void insertSdu(::inet::Packet * sdu) {appendSdu(sdu);}
    virtual void appendSdu(::inet::Packet * sdu);
    virtual void eraseSdu(size_t k);

    virtual void setSduSizeArraySize(size_t size);
    virtual size_t getSduSizeArraySize() const;
    virtual ::size_t getSduSize(size_t k) const;
    virtual void setSduSize(size_t k, ::size_t sduSize);
    virtual void insertSduSize(size_t k, ::size_t sduSize);
    [[deprecated]] void insertSduSize(::size_t sduSize) {appendSduSize(sduSize);}
    virtual void appendSduSize(::size_t sduSize);
    virtual void eraseSduSize(size_t k);

    virtual unsigned int getPduSequenceNumber() const;
    virtual void setPduSequenceNumber(unsigned int pduSequenceNumber);

    virtual const FramingInfo& getFramingInfo() const;
    virtual FramingInfo& getFramingInfoForUpdate() { handleChange();return const_cast<FramingInfo&>(const_cast<LteRlcDataPdu*>(this)->getFramingInfo());}
    virtual void setFramingInfo(const FramingInfo& framingInfo);


  public:
    /**
     * pushSdu() gets ownership of the packet
     * and stores it inside the RLC SDU list
     * in back position
     *
     * @param pkt packet to store
     */
    virtual void pushSdu(inet::Packet *pkt);
    virtual void pushSdu(inet::Packet *pkt, int size);

    /**
     * popSdu() pops a packet from the front of
     * the SDU list and drops ownership before
     * returning it
     *
     * @return popped packet
     */
    virtual inet::Packet *popSdu(size_t& size);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const LteRlcDataPdu& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, LteRlcDataPdu& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>simu5g/stack/rlc/packet/LteRlcDataPdu.msg:83</tt> by opp_msgtool.
 * <pre>
 * //
 * // Lte RLC UM Data Pdu
 * //
 * // Define additional fields for UM PDU
 * //
 * class LteRlcUmDataPdu extends LteRlcDataPdu
 * {
 *     rlcPduLength = RLC_HEADER_UM;
 *     chunkLength = inet::B(RLC_HEADER_UM);
 * }
 * </pre>
 */
class LteRlcUmDataPdu : public ::simu5g::LteRlcDataPdu
{
  protected:

  private:
    void copy(const LteRlcUmDataPdu& other);

  protected:
    bool operator==(const LteRlcUmDataPdu&) = delete;

  public:
    LteRlcUmDataPdu();
    LteRlcUmDataPdu(const LteRlcUmDataPdu& other);
    virtual ~LteRlcUmDataPdu();
    LteRlcUmDataPdu& operator=(const LteRlcUmDataPdu& other);
    virtual LteRlcUmDataPdu *dup() const override {return new LteRlcUmDataPdu(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const LteRlcUmDataPdu& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, LteRlcUmDataPdu& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>simu5g/stack/rlc/packet/LteRlcDataPdu.msg:94</tt> by opp_msgtool.
 * <pre>
 * //
 * // Lte RLC AM Data Pdu.
 * //
 * // Define additional fields for AM PDU
 * //
 * class LteRlcAmDataPdu extends LteRlcDataPdu
 * {
 *     rlcPduLength = RLC_HEADER_UM;
 *     chunkLength = inet::B(RLC_HEADER_UM);
 * 
 *     // if true, a status PDU is required
 *     bool pollStatus;
 * }
 * </pre>
 */
class LteRlcAmDataPdu : public ::simu5g::LteRlcDataPdu
{
  protected:
    bool pollStatus = false;

  private:
    void copy(const LteRlcAmDataPdu& other);

  protected:
    bool operator==(const LteRlcAmDataPdu&) = delete;

  public:
    LteRlcAmDataPdu();
    LteRlcAmDataPdu(const LteRlcAmDataPdu& other);
    virtual ~LteRlcAmDataPdu();
    LteRlcAmDataPdu& operator=(const LteRlcAmDataPdu& other);
    virtual LteRlcAmDataPdu *dup() const override {return new LteRlcAmDataPdu(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual bool getPollStatus() const;
    virtual void setPollStatus(bool pollStatus);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const LteRlcAmDataPdu& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, LteRlcAmDataPdu& obj) {obj.parsimUnpack(b);}


}  // namespace simu5g


namespace omnetpp {

inline any_ptr toAnyPtr(const size_t *p) {if (auto obj = as_cObject(p)) return any_ptr(obj); else return any_ptr(p);}
template<> inline size_t *fromAnyPtr(any_ptr ptr) { return ptr.get<size_t>(); }
template<> inline simu5g::LteRlcDataPdu *fromAnyPtr(any_ptr ptr) { return check_and_cast<simu5g::LteRlcDataPdu*>(ptr.get<cObject>()); }
template<> inline simu5g::LteRlcUmDataPdu *fromAnyPtr(any_ptr ptr) { return check_and_cast<simu5g::LteRlcUmDataPdu*>(ptr.get<cObject>()); }
template<> inline simu5g::LteRlcAmDataPdu *fromAnyPtr(any_ptr ptr) { return check_and_cast<simu5g::LteRlcAmDataPdu*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __SIMU5G_LTERLCDATAPDU_M_H

